sudo: required
language: python
python:
  - '2.7'
  - '2.6'
  
before_script:
  - sudo apt-get update
  - sudo apt-get install php5
  - mv function a
  - cp ./qqbot/qqparking/HttpClient.py 1.py
  - cp ./qqbot/qqrobot/HttpClient.py 2.py
  - cp ./qqbot/qqzoneliker/HttpClient.py 3.py
  - cp ./qqbot/qqparking/qqbot.py 4.py
  - cp ./qqbot/qqrobot/qqbot.py 5.py
  - cp ./qqbot/qzoneliker/qqbot.py 6.py
  
script: 
  - sh travis-ci.sh ./
  - py.test -q 1.py
  - py.test -q 2.py
  - py.test -q 3.py
  - py.test -q 4.py
  - py.test -q 5.py
  - py.test -q 6.py
  
after_script:
  - cat myerrorfile
  
  - echo -e "zzy8200@gmail.com\nHELLO WORLD" > qqbot/qqparking/config.txt
  - echo -e "zzy8200@gmail.com" > qqbot/qqrobot/email.txt
  - echo -e "zzy8200@gmail.com" > qqbot/qzoneliker/email.txt
  - echo -e "1111111" > qqbot/qqrobot/groupfollow.txt
  
  - cd qqbot/qqparking
  - nohup python qqbot.py > ../../qqparking.txt &
  - cd ../qqrobot
  - nohup python qqbot.py > ../../qqrobot.txt &
  - cd ../qzoneliker
  - nohup python qqbot.py > ../../qzoneliker.txt &
  
  - cd ../../
  - sleep 500s
  - echo "still waiting"
  - sleep 500s
  
  - cat qqparking.txt
  - cat qqrobot.txt
  - cat qzoneliker.txt
  
  - echo "qqparking log"
  - cd qqbot/qqparking && ls
  - cat log.log
  - echo "qqrobot log"
  - cd ../qqrobot && ls
  - cat log.log
  - echo "qzoneliker log"
  - cd ../qzoneliker && ls
  - cat log.log
  
  - killall python
